spring:
  application:
    name: view
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    prefix: classpath:/templates/
    cache: false

  data:
    mongodb:
      port: 27017
      database: recommender
      host: localhost

mongo:
  host: localhost
  port: 27017

redis:
  host: 127.0.0.1

server:
  port: 8090